* Bday 

  ** ADVISORY
  + This is for MY personal education only in my attempt to learn Property-Based Testing
    from a highly recommended book.
  + While I am using code and techniques from the book, It is NOT my intention
    to turn this into a direct port, I am also learning Common Lisp and how to do PBT in CL.
  
Birthday greetings kata used for Property-Based Testing.
Guided by and based on "Property-Based Testing with PropEr, Erlang and Elixir by Fred Hebert"
Part II - Stateless Propertise in Practice
Chapter 5. Responsible Testing

** Usage

** Installation

```(ql:quickload '("cl-csv" "postmaster" "bday"))```

*** Testing
Load the required packages first: 
```(ql:quickload '(:mockingbird :postmaster-mock cl-quickcheck))```
Then:
```(asdf:test-system "bday")```

** Author

+ Jason S. Robinson (json.robinson@gmail.com)

** Copyright

The original Erlang / Elixer code and concepts are from Frank Hebert, this is just my
attempt at applying them in Common Lisp to have a better grasp on the concept.

** License


